# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gog.protocols.pb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gog.protocols.pb.proto\x12\x10gog.protocols.pb\"M\n\x06Header\x12\x0c\n\x04sort\x18\x01 \x02(\r\x12\x0c\n\x04type\x18\x02 \x02(\r\x12\x0f\n\x04size\x18\x03 \x01(\r:\x01\x30\x12\x0c\n\x04oseq\x18\x04 \x01(\r*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\xa9\x03\n\x08Response\"\xc7\x01\n\x06Status\x12\x14\n\x10UNKNOWN_RESPONSE\x10\x00\x12\x07\n\x02OK\x10\xc8\x01\x12\r\n\x08\x41\x43\x43\x45PTED\x10\xca\x01\x12\x10\n\x0b\x42\x41\x44_REQUEST\x10\x90\x03\x12\x11\n\x0cUNAUTHORIZED\x10\x91\x03\x12\x0e\n\tFORBIDDEN\x10\x93\x03\x12\x0e\n\tNOT_FOUND\x10\x94\x03\x12\r\n\x08\x43ONFLICT\x10\x99\x03\x12\x13\n\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x14\n\x0fNOT_IMPLEMENTED\x10\xf5\x03\x12\x10\n\x0bUNAVAILABLE\x10\xf7\x03\x32&\n\x04rseq\x12\x18.gog.protocols.pb.Header\x18\x64 \x01(\r2M\n\x04\x63ode\x12\x18.gog.protocols.pb.Header\x18\x65 \x01(\x0e\x32!.gog.protocols.pb.Response.Status:\x02OK2-\n\x0b\x64\x65scription\x12\x18.gog.protocols.pb.Header\x18\x66 \x01(\t2-\n\x0bretry_after\x12\x18.gog.protocols.pb.Header\x18g \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gog.protocols.pb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  Header.RegisterExtension(_RESPONSE.extensions_by_name['rseq'])
  Header.RegisterExtension(_RESPONSE.extensions_by_name['code'])
  Header.RegisterExtension(_RESPONSE.extensions_by_name['description'])
  Header.RegisterExtension(_RESPONSE.extensions_by_name['retry_after'])

  DESCRIPTOR._options = None
  _HEADER._serialized_start=44
  _HEADER._serialized_end=121
  _RESPONSE._serialized_start=124
  _RESPONSE._serialized_end=549
  _RESPONSE_STATUS._serialized_start=137
  _RESPONSE_STATUS._serialized_end=336
# @@protoc_insertion_point(module_scope)
