# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.protocols.overlay_for_peer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'galaxy.protocols.overlay_for_peer.proto\x12!galaxy.protocols.overlay_for_peer\")\n\x17StateChangeNotification\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\"/\n\x1cVisibilityChangeNotification\x12\x0f\n\x07visible\x18\x01 \x01(\x08\"1\n\x14ShowInvitationDialog\x12\x19\n\x11\x63onnection_string\x18\x01 \x01(\t\"_\n\x1bGameJoinRequestNotification\x12\x12\n\ninviter_id\x18\x01 \x01(\x04\x12\x19\n\x11\x63onnection_string\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"\x1a\n\x0bShowWebPage\x12\x0b\n\x03url\x18\x01 \x01(\t\"M\n\x1aGameInviteSentNotification\x12\x14\n\x0creceiver_ids\x18\x01 \x03(\x04\x12\x19\n\x11\x63onnection_string\x18\x02 \x01(\t\"(\n\rDisablePopups\x12\x17\n\x0f\x64isabled_popups\x18\x01 \x01(\x08*\x1f\n\x0bMessageSort\x12\x10\n\x0cMESSAGE_SORT\x10\x06*\x99\x02\n\x0bMessageType\x12\x13\n\x0fUNKNOWN_MESSAGE\x10\x00\x12\x1d\n\x19STATE_CHANGE_NOTIFICATION\x10\x01\x12\"\n\x1eVISIBILITY_CHANGE_NOTIFICATION\x10\x01\x12\x1a\n\x16SHOW_INVITATION_DIALOG\x10\x02\x12\"\n\x1eGAME_JOIN_REQUEST_NOTIFICATION\x10\x03\x12\x11\n\rSHOW_WEB_PAGE\x10\x04\x12!\n\x1dGAME_INVITE_SENT_NOTIFICATION\x10\x05\x12$\n OVERLAY_INITIALIZED_NOTIFICATION\x10\x06\x12\x12\n\x0e\x44ISABLE_POPUPS\x10\x06\x1a\x02\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy.protocols.overlay_for_peer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._options = None
  _MESSAGETYPE._serialized_options = b'\020\001'
  _MESSAGESORT._serialized_start=467
  _MESSAGESORT._serialized_end=498
  _MESSAGETYPE._serialized_start=501
  _MESSAGETYPE._serialized_end=782
  _STATECHANGENOTIFICATION._serialized_start=78
  _STATECHANGENOTIFICATION._serialized_end=119
  _VISIBILITYCHANGENOTIFICATION._serialized_start=121
  _VISIBILITYCHANGENOTIFICATION._serialized_end=168
  _SHOWINVITATIONDIALOG._serialized_start=170
  _SHOWINVITATIONDIALOG._serialized_end=219
  _GAMEJOINREQUESTNOTIFICATION._serialized_start=221
  _GAMEJOINREQUESTNOTIFICATION._serialized_end=316
  _SHOWWEBPAGE._serialized_start=318
  _SHOWWEBPAGE._serialized_end=344
  _GAMEINVITESENTNOTIFICATION._serialized_start=346
  _GAMEINVITESENTNOTIFICATION._serialized_end=423
  _DISABLEPOPUPS._serialized_start=425
  _DISABLEPOPUPS._serialized_end=465
# @@protoc_insertion_point(module_scope)
