# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.protocols.webbroker_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(galaxy.protocols.webbroker_service.proto\x12\"galaxy.protocols.webbroker_service\"!\n\x0b\x41uthRequest\x12\x12\n\nauth_token\x18\x01 \x01(\t\"&\n\x15SubscribeTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\'\n\x16SubscribeTopicResponse\x12\r\n\x05topic\x18\x01 \x01(\t\">\n\x10MessageFromTopic\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x04*\x1f\n\x0bMessageSort\x12\x10\n\x0cMESSAGE_SORT\x10\x02*\x9a\x01\n\x0bMessageType\x12\x13\n\x0fUNKNOWN_MESSAGE\x10\x00\x12\x10\n\x0c\x41UTH_REQUEST\x10\x01\x12\x11\n\rAUTH_RESPONSE\x10\x02\x12\x1b\n\x17SUBSCRIBE_TOPIC_REQUEST\x10\x03\x12\x1c\n\x18SUBSCRIBE_TOPIC_RESPONSE\x10\x04\x12\x16\n\x12MESSAGE_FROM_TOPIC\x10\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy.protocols.webbroker_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGESORT._serialized_start=260
  _MESSAGESORT._serialized_end=291
  _MESSAGETYPE._serialized_start=294
  _MESSAGETYPE._serialized_end=448
  _AUTHREQUEST._serialized_start=80
  _AUTHREQUEST._serialized_end=113
  _SUBSCRIBETOPICREQUEST._serialized_start=115
  _SUBSCRIBETOPICREQUEST._serialized_end=153
  _SUBSCRIBETOPICRESPONSE._serialized_start=155
  _SUBSCRIBETOPICRESPONSE._serialized_end=194
  _MESSAGEFROMTOPIC._serialized_start=196
  _MESSAGEFROMTOPIC._serialized_end=258
# @@protoc_insertion_point(module_scope)
