# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.common.protocols.connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(galaxy.common.protocols.connection.proto\x12\"galaxy.common.protocols.connection\"\x19\n\x04Ping\x12\x11\n\tping_time\x18\x01 \x01(\r\"\x19\n\x04Pong\x12\x11\n\tping_time\x18\x01 \x01(\r*6\n\x0bMessageType\x12\x13\n\x0fUNKNOWN_MESSAGE\x10\x00\x12\x08\n\x04PING\x10\x01\x12\x08\n\x04PONG\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy.common.protocols.connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=134
  _MESSAGETYPE._serialized_end=188
  _PING._serialized_start=80
  _PING._serialized_end=105
  _PONG._serialized_start=107
  _PONG._serialized_end=132
# @@protoc_insertion_point(module_scope)
