# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.common.protocols.peer_to_peer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galaxy.common.protocols import peer_common_pb2 as galaxy_dot_common_dot_protocols_dot_peer__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*galaxy.common.protocols.peer_to_peer.proto\x12$galaxy.common.protocols.peer_to_peer\x1a)galaxy.common.protocols.peer_common.proto\"\xe3\x01\n\x1bLobbyPropertiesNotification\x12\x10\n\x08lobby_id\x18\x01 \x01(\x04\x12\x41\n\nproperties\x18\x02 \x03(\x0b\x32-.galaxy.common.protocols.peer_common.Property\x12\x18\n\x10member_max_count\x18\x03 \x01(\r\x12\x43\n\nlobby_type\x18\x04 \x01(\x0e\x32/.galaxy.common.protocols.peer_to_peer.LobbyType\x12\x10\n\x08joinable\x18\x05 \x01(\x08\"x\n!LobbyMemberPropertiesNotification\x12\x10\n\x08lobby_id\x18\x01 \x01(\x04\x12\x41\n\nproperties\x18\x03 \x03(\x0b\x32-.galaxy.common.protocols.peer_common.Property\"L\n\x0c\x43ustomPacket\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\x10\n\x08lobby_id\x18\x03 \x01(\x04\x12\x0b\n\x03seq\x18\x04 \x01(\x04\".\n\x0cLobbyMessage\x12\x10\n\x08lobby_id\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t*\x95\x01\n\x0bMessageType\x12\x13\n\x0fUNKNOWN_MESSAGE\x10\x00\x12!\n\x1dLOBBY_PROPERTIES_NOTIFICATION\x10\x01\x12(\n$LOBBY_MEMBER_PROPERTIES_NOTIFICATION\x10\x02\x12\x11\n\rCUSTOM_PACKET\x10\x03\x12\x11\n\rLOBBY_MESSAGE\x10\x04*|\n\tLobbyType\x12\x16\n\x12LOBBY_TYPE_PRIVATE\x10\x00\x12\x1b\n\x17LOBBY_TYPE_FRIENDS_ONLY\x10\x01\x12\x15\n\x11LOBBY_TYPE_PUBLIC\x10\x02\x12#\n\x1fLOBBY_TYPE_INVISIBLE_TO_FRIENDS\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy.common.protocols.peer_to_peer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=606
  _MESSAGETYPE._serialized_end=755
  _LOBBYTYPE._serialized_start=757
  _LOBBYTYPE._serialized_end=881
  _LOBBYPROPERTIESNOTIFICATION._serialized_start=128
  _LOBBYPROPERTIESNOTIFICATION._serialized_end=355
  _LOBBYMEMBERPROPERTIESNOTIFICATION._serialized_start=357
  _LOBBYMEMBERPROPERTIESNOTIFICATION._serialized_end=477
  _CUSTOMPACKET._serialized_start=479
  _CUSTOMPACKET._serialized_end=555
  _LOBBYMESSAGE._serialized_start=557
  _LOBBYMESSAGE._serialized_end=603
# @@protoc_insertion_point(module_scope)
