pub static GALAXY_CLIENT_ID: &str = "46899977096215655";
pub static NOTIFICATIONS_PUSHER_SOCKET: &str = "wss://notifications-pusher.gog.com/";

use crate::api::structs::Token;
use std::{collections::HashMap, sync::Arc};
use tokio::sync::Mutex;

pub type TokenStorage = Arc<Mutex<HashMap<String, Token>>>;

pub static GALAXY_INIT_DATA: &str = r#"{"Languages":[{"Code":"en","EnglishName":"English","NativeName":"English"},{"Code":"de","EnglishName":"German","NativeName":"Deutsch"},{"Code":"fr","EnglishName":"French","NativeName":"Français"},{"Code":"ru","EnglishName":"Russian","NativeName":"Русский"},{"Code":"pl","EnglishName":"Polish","NativeName":"Polski"},{"Code":"es","EnglishName":"Spanish","NativeName":"Español"},{"Code":"it","EnglishName":"Italian","NativeName":"Italiano"},{"Code":"jp","EnglishName":"Japanese","NativeName":"日本語"},{"Code":"ko","EnglishName":"Korean","NativeName":"한국어"},{"Code":"pt","EnglishName":"Portuguese","NativeName":"Português"},{"Code":"tr","EnglishName":"Turkish","NativeName":"Türkçe"},{"Code":"cz","EnglishName":"Czech","NativeName":"Čeština"},{"Code":"cn","EnglishName":"Chinese","NativeName":"中文"},{"Code":"hu","EnglishName":"Hungarian","NativeName":"Magyar"},{"Code":"nl","EnglishName":"Dutch","NativeName":"Nederlands"},{"Code":"ho","EnglishName":"Hiri Motu","NativeName":"Hiri Motu"},{"Code":"ro","EnglishName":"Romanian","NativeName":"Română"}],"SettingsData":{"languageCode":"en-US","notifChatMessage":true,"notifDownloadStatus":true,"notifDownloadStatus_overlay":true,"notifFriendInvite":true,"notifFriendOnline":true,"notifFriendStartsGame":true,"notifGameInvite":true,"notifSoundChatMessage":true,"notifSoundDownloadStatus":false,"notifSoundFriendInvite":true,"notifSoundFriendOnline":false,"notifSoundFriendStartsGame":false,"notifSoundGameInvite":true,"notifSoundVolume":50,"showFriendsSidebar":true,"store":{}},"Endpoints":{"api":"https://api.gog.com","chat":"https://chat.gog.com","externalAccounts":"https://external-accounts.gog.com","externalUsers":"https://external-users.gog.com","gameplay":"https://gameplay.gog.com","gog":"https://embed.gog.com","gogGalaxyStoreApi":"https://embed.gog.com","notifications":"https://notifications.gog.com","pusher":"https://notifications-pusher.gog.com","library":"https://galaxy-library.gog.com","presence":"https://presence.gog.com","users":"https://users.gog.com","redeem":"https://redeem.gog.com","marketingSections":"https://marketing-sections.gog.com","galaxyPromos":"https://galaxy-promos.gog.com","remoteConfigurationHost":"https://remote-config.gog.com","recommendations":"https://recommendations-api.gog.com"},"ClientId":"46899977096215655","ChangelogBasePath":"","ClientVersions":{"Major":2,"Minor":0,"Build":61,"Compilation":1},"StartupPage":"discover_view"}"#;
