name: Build on push (Documentation add test)

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Checking repository
        run: ls $GITHUB_WORKSPACE
      - name: Setup target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}
      - name: Add Steam Deck shortcut files
        run: | 
          cp $GITHUB_WORKSPACE/steamdeck/comet_shortcut.sh target/${{ matrix.target }}/release/comet_shortcut.sh
          cp $GITHUB_WORKSPACE/steamdeck/USAGE.md target/${{ matrix.target }}/release/USAGE.md
      - uses: actions/upload-artifact@v4
        with:
          name: comet-${{ matrix.target }}
          path: | 
            target/${{ matrix.target }}/release/${{ contains(matrix.target, 'pc-windows') && 'comet.exe' || 'comet' }}
            target/${{ matrix.target }}/release/comet_shortcut.sh
            target/${{ matrix.target }}/release/USAGE.md
